SmartAgentMonitoring/Models/DeviceIOModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DeviceMonitoring.Models
{
    public class DeviceIOModel
    {
        public bool Input0 { get; set; }
        public bool Output0 { get; set; }
    }
}

SmartAgentMonitoring/Models/ErrorViewModel.cs
using System;

namespace DeviceMonitoring.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SmartAgentMonitoring/Controllers/DeviceMonitoringController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.AspNetCore.SignalR.Client;
using System.Net.Http;
using System.Net;

namespace DeviceMonitoring.Controllers
{
    // This is the conroller for the SmartAgent IO Monitoring
    public class DeviceMonitoringController : Controller
    {
        private readonly IHubContext<MonitoringHub> _hubContext;

        public DeviceMonitoringController(IHubContext<MonitoringHub> hubContext)
        {
            _hubContext = hubContext;
        }

        public ActionResult Index()
        {
            var hostName = HttpContext.Request.Host.ToString().Split(":");
            ViewData["DevicePortalWebsite"] = "http://" + hostName[0] + ":8080";
            return View();
        }

        [HttpPut]
        public HttpResponseMessage UpdateSingleInputState([FromBody] PinState pinState)
        {
            try
            {
                _hubContext.Clients.All.InvokeAsync("UpdateSingleInputState", pinState);
                return new HttpResponseMessage(HttpStatusCode.OK);
            }

            catch (Exception ex)
            {
                return new HttpResponseMessage(HttpStatusCode.Conflict);
            }
        }

        [HttpPut]
        public HttpResponseMessage UpdateSingleOutputState([FromBody] PinState pinState)
        {
            try
            {
                _hubContext.Clients.All.InvokeAsync("UpdateSingleOutputState", pinState);
                return new HttpResponseMessage(HttpStatusCode.OK);
            }

            catch (Exception ex)
            {
                return new HttpResponseMessage(HttpStatusCode.Conflict);
            }
        }
    }
}

SmartAgentMonitoring/Controllers/GatewayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace SmartAgentMonitoring.Controllers
{
    public class GatewayController : Controller
    {
        // GET: Gateway
        public ActionResult Index()
        {
            var hostName = HttpContext.Request.Host.ToString().Split(":");
            ViewData["DevicePortalWebsite"] = "http://" + hostName[0] + ":8080";
            return View();
        }
    }
}

SmartAgentMonitoring/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using DeviceMonitoring.Models;

namespace DeviceMonitoring.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SmartAgentMonitoring/Views/DeviceMonitoring/Index.cshtml
@{
//  Layout = null;
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SmartAgent Monitoring</title>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link href="~/css/deviceMonitoring.css" rel="stylesheet" />
    <script src="~/lib/signalr-client-1.0.0-alpha2-final.min.js"></script>

</head>

<body>

    <script>
        $(document).ready(function () {

            let hubConnection = new signalR.HubConnection('/MonitoringHub');

            hubConnection.on('UpdateSingleInputState', function (pinState) {
                var state = pinState.state;
                var pinNumber = pinState.pinNumber;

                if (state == true) {
                    setInputTrue(pinNumber)
                }
                else {
                    setInputFalse(pinNumber)
                }
            });

            hubConnection.on('UpdateSingleOutputState', function (pinState) {

                var state = pinState.state;
                var pinNumber = pinState.pinNumber;

                if (state == true) {
                    setOutputTrue(pinNumber)
                }

                else {
                    setOutputFalse(pinNumber)
                }
            });

            hubConnection.on('UpdateAllInputStates', function (inputStates) {

                var listLength = inputStates.length;

                for (var i = 0; i < listLength; i++) {

                    var state = inputStates[i].state;
                    var pinNumber = inputStates[i].pinNumber;
                    if (state == true) {
                        setInputTrue(pinNumber)
                    }

                    else {
                        setInputFalse(pinNumber)
                    }
                }
            });

            hubConnection.on('UpdateAllOutputStates', function (outputStates) {

                var listLength = outputStates.length;
                for (var i = 0; i < listLength; i++) {

                    var state = outputStates[i].state;
                    var pinNumber = outputStates[i].pinNumber;
                    if (state == true) {
                        setOutputTrue(pinNumber)
                    }
                    else {
                        setOutputFalse(pinNumber)
                    }
                }
            });

            hubConnection.on('UpdateClientCounter', function (numberOfClients) {
                $("#clientCounter").text("connected Clients: " + numberOfClients);
            });

            $(".input_on").click(function () {
                var state = true;
                var pinNumber = this.value;
                hubConnection.invoke('SetDeviceInput', pinNumber, state);
            });


            function setInputTrue(pinNumber) {
                inputIconId = "#inputIco" + pinNumber;
                $(inputIconId).addClass("io_on");
            }


            function setInputFalse(pinNumber) {
                inputIconId = "#inputIco" + pinNumber;
                $(inputIconId).removeClass("io_on");
            }



            $(".input_off").click(function () {
                var state = false;
                var pinNumber = this.value;
                hubConnection.invoke('SetDeviceInput', pinNumber, state);
            });


            $(".output_on").click(function () {
                var state = true;
                var pinNumber = this.value;
                hubConnection.invoke('SetDeviceOutput', pinNumber, state);
            });


            $(".output_off").click(function () {
                var state = false;
                var pinNumber = this.value;
                hubConnection.invoke('SetDeviceOutput', pinNumber, state);
            });

            function setOutputTrue(pinNumber) {
                outputIconId = "#outputIco" + pinNumber;
                $(outputIconId).addClass("io_on");
            }


            function setOutputFalse(pinNumber) {
                outputIconId = "#outputIco" + pinNumber;
                $(outputIconId).removeClass("io_on");
            }
            hubConnection.start();

        });

    </script>

    <h1>SmartAgent IO Monitoring</h1>

    <h2 id="clientCounter">initialising... </h2>

    <h2 class="ioTitle">Inputs</h2>

    <div class="inputTable">

        <span>
            <button class="input_off" value="0" type="button">Set 0</button>
            <button class="input_on" value="0" type="button">Set 1</button>
        </span>

        <div class="inputBorderClass">
            <span class="inputHead">0</span>
            <span id="inputIco0" class="inputIco"><i></i></span>
            <span class="inputList">
                <ul>
                    <li>counter: </li>
                </ul>
            </span>
        </div>
    </div>
    <div class="inputTable">
        <span>
            <button class="input_off" value="1" type="button">Set 0</button>
            <button class="input_on" value="1" type="button">Set 1</button>
        </span>

        <div class="inputBorderClass">
            <span class="inputHead">1</span>
            <span id="inputIco1" class="inputIco"><i></i></span>
            <span class="inputList">
                <ul>
                    <li>counter: </li>
                </ul>
            </span>
        </div>
    </div>
    <div class="inputTable">
        <span>
            <button class="input_off" value="2" type="button">Set 0</button>
            <button class="input_on" value="2" type="button">Set 1</button>
        </span>

        <div class="inputBorderClass">
            <span class="inputHead">2</span>
            <span id="inputIco2" class="inputIco"><i></i></span>
            <span class="inputList">
                <ul>
                    <li>counter: </li>
                </ul>
            </span>
        </div>
    </div>

    <div class="inputTable">
        <span>
            <button class="input_off" value="3" type="button">Set 0</button>
            <button class="input_on" value="3" type="button">Set 1</button>
        </span>

        <div class="inputBorderClass">
            <span class="inputHead">3</span>
            <span id="inputIco3" class="inputIco"><i></i></span>
            <span class="inputList">
                <ul>
                    <li>counter: </li>
                </ul>
            </span>
        </div>
    </div>

    <div class="inputTable">
        <span>
            <button class="input_off" value="4" type="button">Set 0</button>
            <button class="input_on" value="4" type="button">Set 1</button>
        </span>

        <div class="inputBorderClass">
            <span class="inputHead">4</span>
            <span id="inputIco4" class="inputIco"><i></i></span>
            <span class="inputList">
                <ul>
                    <li>counter: </li>
                </ul>
            </span>
        </div>
    </div>
    <div class="inputTable">
        <span>
            <button class="input_off" value="5" type="button">Set 0</button>
            <button class="input_on" value="5" type="button">Set 1</button>
        </span>

        <div class="inputBorderClass">
            <span class="inputHead">5</span>
            <span id="inputIco5" class="inputIco"><i></i></span>
            <span class="inputList">
                <ul>
                    <li>counter: </li>
                </ul>
            </span>
        </div>
    </div>
    <div class="inputTable">
        <span>
            <button class="input_off" value="6" type="button">Set 0</button>
            <button class="input_on" value="6" type="button">Set 1</button>
        </span>

        <div class="inputBorderClass">
            <span class="inputHead">6</span>
            <span id="inputIco6" class="inputIco"><i></i></span>
            <span class="inputList">
                <ul>
                    <li>counter: </li>
                </ul>
            </span>
        </div>
    </div>

    <div class="inputTable">
        <span>
            <button class="input_off" value="7" type="button">Set 0</button>
            <button class="input_on" value="7" type="button">Set 1</button>
        </span>

        <div class="inputBorderClass">
            <span class="inputHead">7</span>
            <span id="inputIco7" class="inputIco"><i></i></span>
            <span class="inputList">
                <ul>
                    <li>counter: </li>
                </ul>
            </span>
        </div>
    </div>



    <h2 class="ioTitle" id="ioTitleOutput">Outputs</h2>

    <div class="outputTable">

        <span>
            <button class="output_off" value="0" type="button">Set 0</button>
            <button class="output_on" value="0" type="button">Set 1</button>
        </span>

        <div class="outputBorderClass">
            <span class="outputHead">0</span>
            <span id="outputIco0" class="outputIco"><i></i></span>
            <span class="outputList">
                <ul>
                    <li>counter: </li>
                </ul>
            </span>
        </div>
    </div>
    <div class="outputTable">
        <span>
            <button class="output_off" value="1" type="button">Set 0</button>
            <button class="output_on" value="1" type="button">Set 1</button>
        </span>

        <div class="outputBorderClass">
            <span class="outputHead">1</span>
            <span id="outputIco1" class="outputIco"><i></i></span>
            <span class="outputList">
                <ul>
                    <li>counter: </li>
                </ul>
            </span>
        </div>
    </div>
    <div class="outputTable">
        <span>
            <button class="output_off" value="2" type="button">Set 0</button>
            <button class="output_on" value="2" type="button">Set 1</button>
        </span>

        <div class="outputBorderClass">
            <span class="outputHead">2</span>
            <span id="outputIco2" class="outputIco"><i></i></span>
            <span class="outputList">
                <ul>
                    <li>counter: </li>
                </ul>
            </span>
        </div>
    </div>

    <div class="outputTable">
        <span>
            <button class="output_off" value="3" type="button">Set 0</button>
            <button class="output_on" value="3" type="button">Set 1</button>
        </span>

        <div class="outputBorderClass">
            <span class="outputHead">3</span>
            <span id="outputIco3" class="outputIco"><i></i></span>
            <span class="outputList">
                <ul>
                    <li>counter: </li>
                </ul>
            </span>
        </div>
    </div>

    <div class="outputTable">
        <span>
            <button class="output_off" value="4" type="button">Set 0</button>
            <button class="output_on" value="4" type="button">Set 1</button>
        </span>

        <div class="outputBorderClass">
            <span class="outputHead">4</span>
            <span id="outputIco4" class="outputIco"><i></i></span>
            <span class="outputList">
                <ul>
                    <li>counter: </li>
                </ul>
            </span>
        </div>
    </div>
    <div class="outputTable">
        <span>
            <button class="output_off" value="5" type="button">Set 0</button>
            <button class="output_on" value="5" type="button">Set 1</button>
        </span>

        <div class="outputBorderClass">
            <span class="outputHead">5</span>
            <span id="outputIco5" class="outputIco"><i></i></span>
            <span class="outputList">
                <ul>
                    <li>counter: </li>
                </ul>
            </span>
        </div>
    </div>
    <div class="outputTable">
        <span>
            <button class="output_off" value="6" type="button">Set 0</button>
            <button class="output_on" value="6" type="button">Set 1</button>
        </span>

        <div class="outputBorderClass">
            <span class="outputHead">6</span>
            <span id="outputIco6" class="outputIco"><i></i></span>
            <span class="outputList">
                <ul>
                    <li>counter: </li>
                </ul>
            </span>
        </div>
    </div>

    <div class="outputTable">
        <span>
            <button class="output_off" value="7" type="button">Set 0</button>
            <button class="output_on" value="7" type="button">Set 1</button>
        </span>

        <div class="outputBorderClass">
            <span class="outputHead">7</span>
            <span id="outputIco7" class="outputIco"><i></i></span>
            <span class="outputList">
                <ul>
                    <li>counter: </li>
                </ul>
            </span>
        </div>
    </div>
</body>
</html>

SmartAgentMonitoring/Views/Gateway/Index.cshtml
@{
//  Layout = null;
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SmartAgent Gateway</title>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link href="~/css/deviceMonitoring.css" rel="stylesheet" />
    <script src="~/lib/signalr-client-1.0.0-alpha2-final.min.js"></script>

</head>

<body>

    <script>
        $(document).ready(function () {

            let hubConnection = new signalR.HubConnection('/GatewayHub');

            hubConnection.on('UpdateDeviceCounter', function (numberOfConnectedSmartAgents) {
                $("#deviceCounter").text("connected SmartAgents: " + numberOfConnectedSmartAgents);
            });


            hubConnection.on('IsCurrentGateway', function (isCurrentGateway) {
                $("#isCurrentGateway").text("is current gateway: " + isCurrentGateway);
            });

            hubConnection.start();
        });
    </script>

    <h1>SmartAgent Gateway</h1>

    <h2 id="isCurrentGateway">is current gateway: </h2>
    <h2 id="deviceCounter">connected SmartAgents: </h2>
 

 
</body>
</html>

SmartAgentMonitoring/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

SmartAgentMonitoring/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SmartAgentMonitoring/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "DeviceIO";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

SmartAgentMonitoring/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>




    





    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DeviceMonitoring</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="DeviceMonitoring" asp-action="Index" class="navbar-brand">SmartAgent Monitoring</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Gateway" asp-action="Index">Gateway</a></li>
                    <li><a href="@ViewData["DevicePortalWebsite"]">Device Portal</a></li>
                 @*   <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>*@
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; 2017 - DeviceMonitoring</p>*@
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>